env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'eslint:recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-param-reassign: 0
  eqeqeq: 0

